### PR TITLE
[#141948375] Split Consul client and server checks

### PR DESCRIPTION
**Pull request by henrytk**
## What

[#141948375](https://www.pivotaltracker.com/n/projects/1275640/stories/141948375)

Currently we run the Consul server checks on all VMs, because the
    datadog-consul job in this release couples the two together. This
    splits them into those for the client and those for the server.
    
They both have '-agent-' in the name because technically the Consul
    agent process runs both.
    
We also update the sample manifest so it can be tested with bosh-lite,
    which should be much quicker than deploying the whole of CloudFoundry
    with Datadog enabled.

## How to review

If you want to use bosh-lite and avoid having to deploy the whole of CloudFoundry with Datadog enabled you can use the steps below. The job puts config files on the target VM, so we need to assert:

1. that all four checks can still be installed (they were all in one job, but now there are 3 for the client and 1 for the server)
1. that the files are still well-formed

### Using bosh-lite

These instructions are old, but I have tried to update them where possible.

1. Check that you have `vagrant`, `Virtualbox`, and the Bosh CLI installed (you can install bosh_cli with `gem install bosh_cli`).
1. Start bosh-lite:

    ```
    git clone https://github.com/cloudfoundry/bosh-lite && cd bosh-lite
    vagrant up

    bosh target 192.168.50.4 lite # Login: admin Pass: admin
    ```

1. Upload the stemcell:

    ```
    bosh upload stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent?v=3262.2
    ```
    
1. Build the release. `cd` to this repository. Check out this branch and run:

    ```
    bosh create release --with-tarball
    # Change the following path to your created release
    bosh upload release /path/to/release-0+dev.3.tgz
    ```
1. Generate the manifest. There is a script in the manifest/ folder for building manifests. It puts a whole bunch of VMs in there, which you probably don't need and it would take a while downloading and compiling their releases, so you should probably strip them out.

1. Change `DIRECTOR_UUID` to whatever `bosh status --uuid` yields.

1. I can't remember if you need to move the manifest to the vagrant box or whether you can point to it locally and deploy, but you can figure the rest out.

1. `cd` back to your bosh-lite directory and log into the virtual machine:

    ```
    vagrant ssh
    ```
1. Deploy:

    ```
    bosh deployment /tmp/manifest.yml
    bosh deploy
    ```
1. SSH into the virtual machine:

    ```
    bosh ssh consul
    ```

## Who

Anyone but me

### CODE REVIEW

**Comment by dcarley** [comment]
May we should have omitted `-agent` from the job names. Only half joking. 😁

**Comment by mtekel** [comment]
wouldn't hurt. But means re-testing.

**Comment by dcarley** [comment]
I don't feel *really* strongly. I'll let you two figure it out.

**Comment by henrytk** [comment]
I think the name should stay because it is accurate, despite being long. You will have to read it a lot more than you will have to type it, so clarity over brevity.

**Comment by mtekel** [comment]
this works. It's bit of a step away from agentless computing, but we can live with it for now. meging

**Review by mtekel — APPROVED** [review]

**Pull request merged**
